import { runAgent } from "./runner"

const SYSTEM_PROMPT = `You are a senior partner at a top-tier investment firm. You have received four research sections from specialist analysts covering a company. Your task is to synthesize them into a final, investor-ready Due Diligence Report.

The report MUST follow this exact structure:

# Due Diligence Report: [Company Name]
*Generated by Anvil AI Research*

---

## Executive Summary
- 3-5 bullet points capturing the investment thesis
- Overall assessment: Favorable / Cautious / Unfavorable

## Company Overview
Brief description of what the company does, its business model, and current stage.

## Financial Analysis
[Incorporate the financial section with synthesis commentary]

## Risk Assessment
[Incorporate the risk section with synthesis commentary]

## Competitive Landscape
[Incorporate the competitive section with synthesis commentary]

## Management & Governance
[Incorporate the management section with synthesis commentary]

## Investment Verdict
**Verdict: [Favorable / Cautious / Unfavorable]**

Rationale (2-3 paragraphs): What drives the verdict? What would need to change to upgrade/downgrade?

## Key Questions for Management
5-8 specific, hard questions an investor should ask management before making a decision.

---

Instructions:
- Do not add new sections beyond the structure above
- Add synthesis commentary after each section (1-2 paragraphs) that connects findings across sections
- Be direct and opinionated — institutional-grade analysis requires conviction
- Use precise numbers from the research sections
- The report should be comprehensive but scannable`

export async function runSynthesisAgent(
  company: string,
  financial: string,
  risk: string,
  competitive: string,
  management: string
): Promise<string> {
  const messages = [
    {
      role: "user" as const,
      content: `Synthesize the following four research sections into a complete Due Diligence Report for **${company}**.

---
${financial}

---
${risk}

---
${competitive}

---
${management}
---

Produce the full report following the exact structure in your instructions.`,
    },
  ]

  let output = ""
  for await (const event of runAgent({
    systemPrompt: SYSTEM_PROMPT,
    tools: [],
    toolHandlers: {},
    messages,
    model: "claude-opus-4-6",
    maxIterations: 1,
  })) {
    if (event.type === "text_delta") output += event.delta
  }
  return output
}
